### ISSUE TITLE
ErrorException at php artisan db:seed

### ISSUE THREAD

**Issue by parzival42codes** [YasserElgammal/blog-cms#15] opened 2024-04-03 09:31 UTC
I discovered the following problem:

Command: php artisan db:seed

   INFO  Seeding database.  

```

   ErrorException 

  mkdir(): No such file or directory

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:651
    647▕         if ($force) {
    648▕             return @mkdir($path, $mode, $recursive);
    649▕         }
    650▕ 
  ➜ 651▕         return mkdir($path, $mode, $recursive);
    652▕     }
    653▕ 
    654▕     /**
    655▕      * Move a directory.

      +2 vendor frames 

  3   database/factories/PostFactory.php:27
      Illuminate\Support\Facades\Facade::__callStatic("makeDirectory")
      +6 vendor frames 

  10  [internal]:0php artisan db:seed

   INFO  Seeding database.  


   ErrorException 

  mkdir(): No such file or directory

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:651
    647▕         if ($force) {
    648▕             return @mkdir($path, $mode, $recursive);
    649▕         }
    650▕ 
  ➜ 651▕         return mkdir($path, $mode, $recursive);
    652▕     }
    653▕ 
    654▕     /**
    655▕      * Move a directory.

      +2 vendor frames 

  3   database/factories/PostFactory.php:27
      Illuminate\Support\Facades\Facade::__callStatic("makeDirectory")
      +6 vendor frames 

  10  [internal]:0
      Illuminate\Database\Eloquent\Factories\Factory::Illuminate\Database\Eloquent\Factories\{closure}()

      Illuminate\Database\Eloquent\Factories\Factory::Illuminate\Database\Eloquent\Factories\{closure}()

```

**Comment by YasserElgammal** [comment] 2024-04-03 13:09
Hello, 

Thank you for letting me know, the issue is now fixed

**Closed as completed by YasserElgammal** 2024-04-03 13:09 UTC
Labels: good first issue
